//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Microsoft Corporation.")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("© Microsoft Corporation. All rights reserved.")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("A package containing thin abstractions for Microsoft.IdentityModel.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("8.0.0.7010")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("8.0.1+b0f34d51fccc69fd334253924abd8d6853fad7aa")]
[assembly: System.Reflection.AssemblyProductAttribute("Microsoft IdentityModel")]
[assembly: System.Reflection.AssemblyTitleAttribute("Microsoft.IdentityModel.Abstractions")]
[assembly: System.Reflection.AssemblyVersionAttribute("8.0.1.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", ("https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dot" +
    "net"))]

// Generated by the MSBuild WriteCodeFragment class.